CEDS-4104 Change the user's journey flow. The root page is always now the /choice page
hmrc/customs-movements-frontend pull request #392
Opened 2022-09-29 11:25 UTC by udinobi

2022-10-05 10:18 UTC, magicaljellybeans requested changes

2022-10-05 10:18 UTC, magicaljellybeans commented on app/views/ile_query.scala.html
> +@govukLayout(title = Title("ileQuery.title"), backButton = Some(BackButton(messages("site.back"), ChoiceController.displayChoices))) {
Looking at the ticket, the text should be "Back to selection page"

2022-10-05 10:18 UTC, magicaljellybeans commented on app/views/ile_query.scala.html
> +@govukLayout(title = Title("ileQuery.title"), backButton = Some(BackButton(messages("site.back"), ChoiceController.displayChoices))) {
This just says 'Back'

2022-10-05 14:27 UTC, magicaljellybeans approved these changes

2022-10-06 07:22 UTC, glidester approved these changes

2022-10-06 07:24 UTC, merged